model:
  target: cldm.cldm.PAIRDiffusion
  learning_rate: 1.5e-05
  sd_locked: True
  only_mid_control: False
  init_ckpt: './models/pair_diff_init.ckpt'
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: "image"
    cond_stage_key: "caption"
    control_key: "hint"
    image_size: 64
    channels: 4
    cond_stage_trainable: false
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False
    only_mid_control: False
    appearance_net_locked: True
    app_net: 'DINO'

    control_stage_config:
      target: cldm.controlnet.ControlNetPAIR
      params:
        image_size: 32 # unused
        in_channels: 4 
        concat_indices: [0,1]
        concat_channels: 130
        hint_channels: [1026, 1026, -1, -1] #(1024 + 2)
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False
        attn_class: ['maskguided', 'maskguided', 'softmax', 'softmax']

    unet_config:
      target: cldm.cldm.ControlledUnetModel
      params:
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPEmbedder


data:
  target: cldm.data.DataModuleFromConfig
  params:
    batch_size: 2
    wrap: True
    num_workers: 4
    train:
      target: dataset.txtseg.COCOTrain
      params:
        image_dir:
        caption_file:
        panoptic_mask_dir:
        seg_dir:
        size: 512
    validation:
      target: dataset.txtseg.COCOValidation
      params:
        size: 512
        image_dir:
        caption_file:
        panoptic_mask_dir:
        seg_dir:


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 2000
        max_images: 4
        increase_log_steps: False
        log_first_step: True

  trainer:
    benchmark: True
    accumulate_grad_batches: 2